spring:
  application:
    name: MicroserviceRecensioni
  data:    
    uri: mongodb+srv://daniele96:<Daniele96_>@clustermicroservice.erere.mongodb.net/MicroserviceArticoliDB.Microservizi
retryWrites=true&w=majority 
server:
  port: 8081

      
